#include "GitBackupLayer.h"
#include "git_manager.h"
#include "terminal_executor.h"
#include <QFileInfo>
#include <QDir>
#include <QDateTime>
#include <QEventLoop>
#include <QDebug>
#include <algorithm>
#include <QStandardPaths>
#include <QMutex>

GitBackupLayer::GitBackupLayer(QObject *parent)
    : QObject(parent)
{
    initializeExecutor();
    m_gitManager = new GitManager(m_executor, this);
}

GitBackupLayer::~GitBackupLayer()
{
}

void GitBackupLayer::initializeExecutor()
{
    if (!m_executor)
        m_executor = new TerminalExecutor(this);
}

void GitBackupLayer::setRepoPath(const QString &path)
{
    QMutexLocker locker(&m_mutex);
    m_repoPath = path;
    m_gitManager->setRepoPath(path);
}

QString GitBackupLayer::repoPath() const
{
    QMutexLocker locker(&m_mutex);
    return m_repoPath;
}

QString GitBackupLayer::generateCommitMessage(const QString &operation, const QString &filePath)
{
    QString msg = QString("AI Modification: %1").arg(operation);
    if (!filePath.isEmpty()) {
        QFileInfo fi(filePath);
        msg += QString(" — %1").arg(fi.fileName());
    }
    msg += QString("\n\n[Generated by Qt AI Orchestrator]\n"
                   "Timestamp: %1").arg(QDateTime::currentDateTime().toString(Qt::ISODate));
    return msg;
}

bool GitBackupLayer::ensureGitRepo() const
{
    if (m_repoPath.isEmpty())
        return false;
    QFileInfo gitDir(m_repoPath + "/.git");
    return gitDir.exists();
}

bool GitBackupLayer::ensureGitAvailable() const
{
    static QMutex mutex;
    static bool available = false;
    static bool checked = false;

    QMutexLocker locker(&mutex);
    if (checked)
        return available;

    available = !QStandardPaths::findExecutable("git").isEmpty();
    checked = true;
    return available;
}

QString GitBackupLayer::runGit(const QStringList &args)
{
    if (!ensureGitRepo())
        return {};

    if (!ensureGitAvailable()) {
        emit gitError("git executable not found in PATH");
        return "GIT_NOT_FOUND";
    }

    QProcess process;
    process.setWorkingDirectory(m_repoPath);
    process.start("git", args);
    if (!process.waitForStarted(5000)) {
        emit gitError(QString("Failed to start git: %1").arg(process.errorString()));
        return "GIT_START_FAILED";
    }
    if (!process.waitForFinished(30000)) {
        emit gitError("Git command timed out");
        process.kill();
        process.waitForFinished();
        return "GIT_TIMEOUT";
    }
    QString output = QString::fromLocal8Bit(process.readAllStandardOutput());
    QString error = QString::fromLocal8Bit(process.readAllStandardError());
    if (process.exitStatus() != QProcess::NormalExit || process.exitCode() != 0) {
        if (!error.isEmpty())
            output += "\n" + error;
    }
    return output;
}

GitBackupLayer::BackupResult GitBackupLayer::commitBeforeModification(const QString &filePath)
{
    BackupResult result;
    QMutexLocker locker(&m_mutex);

    if (!ensureGitRepo()) {
        result.error = "Not a git repository";
        emit gitError(result.error);
        return result;
    }

    QStringList addArgs = {"add"};
    if (!filePath.isEmpty()) {
        addArgs << filePath;
    } else {
        addArgs << "-A";
    }

    QString addOutput = runGit(addArgs);

    QString commitMsg = generateCommitMessage("Before Refactor", filePath);
    QStringList commitArgs = {"commit", "-m", commitMsg};

    QString commitOutput = runGit(commitArgs);

    if (commitOutput.contains("nothing to commit", Qt::CaseInsensitive)) {
        result.success = true;
        result.message = "Nothing to commit (clean working tree)";
        emit backupCreated(result);
        return result;
    }

    if (commitOutput.contains("[") && commitOutput.contains("]")) {
        int start = commitOutput.indexOf('[');
        int end = commitOutput.indexOf(']', start);
        if (start >= 0 && end > start) {
            result.commitHash = commitOutput.mid(start + 1, end - start - 1).trimmed();
        }
    }

    if (!result.commitHash.isEmpty()) {
        result.success = true;
        result.message = "Backup committed: " + result.commitHash.left(7);
        m_lastCommitHash = result.commitHash;
    } else if (commitOutput.contains("nothing to commit", Qt::CaseInsensitive)) {
        result.success = true;
        result.message = "Nothing to commit";
    } else {
        result.success = false;
        result.error = "Git commit failed: " + commitOutput;
    }

    emit backupCreated(result);
    return result;
}

GitBackupLayer::BackupResult GitBackupLayer::rollback(const QString &filePath)
{
    BackupResult result;
    QMutexLocker locker(&m_mutex);

    if (!ensureGitRepo()) {
        result.error = "Not a git repository";
        emit gitError(result.error);
        return result;
    }

    QStringList args;
    args << "reset" << "--hard" << "HEAD";
    if (!filePath.isEmpty()) {
        args.clear();
        args << "checkout" << "--" << filePath;
    }

    QString output = runGit(args);

    if (output.startsWith("GIT_NOT_FOUND") || output.startsWith("GIT_START_FAILED") || output.startsWith("GIT_TIMEOUT")) {
        result.success = false;
        result.error = output;
    } else if (output.isEmpty() || output.contains("Switched to", Qt::CaseInsensitive) || output.contains("Unstaged changes", Qt::CaseInsensitive)) {
        result.success = true;
        result.message = "Rollback completed";
    } else {
        result.success = false;
        result.error = "Git reset failed: " + output;
    }

    emit rollbackPerformed(result);
    return result;
}

GitBackupLayer::BackupResult GitBackupLayer::commitAfterModification(const QString &message)
{
    BackupResult result;
    QMutexLocker locker(&m_mutex);

    if (!ensureGitRepo()) {
        result.error = "Not a git repository";
        emit gitError(result.error);
        return result;
    }

    QStringList addArgs = {"add", "-A"};
    runGit(addArgs);

    QStringList commitArgs = {"commit", "-m", message};
    QString output = runGit(commitArgs);

    if (output.contains("nothing to commit", Qt::CaseInsensitive)) {
        result.success = true;
        result.message = "Nothing to commit after modification";
    } else if (output.contains("[")) {
        int start = output.indexOf('[');
        int end = output.indexOf(']', start);
        if (start >= 0 && end > start) {
            result.commitHash = output.mid(start + 1, end - start - 1).trimmed();
        }
        result.success = !result.commitHash.isEmpty();
        result.message = result.success ? "Modification committed: " + result.commitHash.left(7) : output;
    } else {
        result.success = false;
        result.error = "Git commit failed: " + output;
    }

    emit backupCreated(result);
    return result;
}

QString GitBackupLayer::lastCommitHash() const
{
    QMutexLocker locker(&m_mutex);
    return m_lastCommitHash;
}

bool GitBackupLayer::hasUncommittedChanges()
{
    QString output = runGit({"status", "--porcelain"});
    return !output.trimmed().isEmpty();
}

QStringList GitBackupLayer::modifiedFiles()
{
    QStringList files;
    QString output = runGit({"status", "--porcelain"});
    QStringList lines = output.split('\n', Qt::SkipEmptyParts);
    for (const QString &line : lines) {
        if (line.length() >= 4) {
            QString file = line.mid(3).trimmed();
            if (!file.isEmpty())
                files.append(file);
        }
    }
    return files;
}
